### ISSUE TITLE
Front end ajax/json

### ISSUE THREAD

**Issue by plwai** [plwai/webtech-assign2#1]
-send data to backend
-receive data and callback

**Comment by DickShern** [comment]
Done:
-send data to backend

**Comment by DickShern** [comment]
![capture](https://cloud.githubusercontent.com/assets/13131032/26001516/37a4b332-375f-11e7-9555-12ac9af78890.PNG)

Currently have bug with inserting data. Blank duplicate is inserted each time.

**Comment by DickShern** [comment]
Done:
-send data to backend

**Comment by DickShern** [comment]
Fixed:
Blank duplicate is inserted each time.

**Comment by DickShern** [comment]
Insert order for 'Fish 'n' chips' causes the following error:
{error: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'n' Chip - Delete', '13.90', '1', 'Lionel Messi')' at line 1", customer: {"name": ["Lionel Messi"],"address": ["Block L07, Jalan Merbau, KTHO"],"area": ["UTM"]}, order: {"item0": ["Fish 'n' Chip - Delete","13.90","1","13.90"]}}

**Comment by DickShern** [comment]
Removed delete href button from insertion into database

**Comment by plwai** [comment]
this is front end issue...

**Comment by DickShern** [comment]
- [ ] test

**Comment by plwai** [comment]
#2 Merged
