### ISSUE TITLE
Backend Database Save Order

### ISSUE THREAD

**Issue by plwai** [plwai/webtech-assign2#14]
@DickShern 

Fish and Chip cannot be save into database. SQL error occurs. Kindly check for it.

![capture](https://cloud.githubusercontent.com/assets/9108726/26529872/6deedcf8-43fb-11e7-8515-b28b42d77622.JPG)

**Comment by plwai** [comment]
Use merged master as your base

**Comment by DickShern** [comment]
Fixed
#15
