### ISSUE TITLE
Quantity * Price Display Problem

### ISSUE THREAD

**Issue by DickShern** [plwai/webtech-assign2#16]
![capture2](https://cloud.githubusercontent.com/assets/13131032/26536491/fc7ae87c-4469-11e7-9255-714f04f7c0c1.PNG)

**Comment by plwai** [comment]
Fixed in #17

**Comment by DickShern** [comment]
![capture](https://cloud.githubusercontent.com/assets/13131032/26538707/01ece68c-447b-11e7-8fcd-7eb14e1237de.PNG)
Same issue.
