### ISSUE TITLE
Clean variable quantity

### ISSUE THREAD

**Issue by DickShern** [plwai/webtech-assign2#5]
![webtech 1](https://cloud.githubusercontent.com/assets/13131032/26479727/0793fd98-4208-11e7-8762-85b1b31ae9cf.PNG)

**Comment by plwai** [comment]
@DickShern  Do u mean the "00"? I just omit it last assignment just because i feel it is not so important in assignment2. In project i will solve it.

**Comment by DickShern** [comment]
yeah, just the 00 part.
