### ISSUE TITLE
List Client Data

### ISSUE THREAD

**Issue by plwai** [plwai/webtech-assign2#7]
List client data according to database table.

- [x] Callback function to change/show the list
- [x] AJAX GET request to server
- [x] Detailed view

**Comment by plwai** [comment]
@DickShern #4 Request to join order data and customer data together.

**Comment by DickShern** [comment]
Ok.  I just finish create the class. I do retrieve customer info next.

**Comment by plwai** [comment]
@DickShern data structure
![image](https://cloud.githubusercontent.com/assets/9108726/26520109/cbdddd9e-42fe-11e7-97d8-6452eb821023.png)

**Comment by plwai** [comment]
#10 #11
